### ISSUE TITLE
Mythril Termination

### ISSUE THREAD

**Issue by elizabethdinella** [ConsenSysDiligence/mythril#1696]
Does mythril terminate only after it has enumerated all possible paths? Or is there some default metric like code coverage / timeout that will allow it to terminate before exhaustively enumerating all paths?

**Comment by norhh** [comment]
Mythril does terminate if one of the following conditions is satisfied:-
1) Execution Timeout runs out
2) All feasible paths are covered, constrained on parameters such as loop-bound (since it's pointless to enumerate a for-loop forever), call-depth (for limiting recursive calls) etc

We do not use code coverage for termination, since the tool is more focused on vulnerability detection than code coverage. Focusing on code coverage can make us miss new vulnerabilities since user X (say owner) executing a piece of code could be safe, whereas user Y (attacker) executing the same code can cause security issues.

**Comment by elizabethdinella** [comment]
Thank you!
